### ISSUE TITLE
Could you add our recent paper published in WSDM

### ISSUE THREAD

**Issue by Zihan-Liu-00** [safe-graph/graph-adversarial-learning-literature#16]
Hi, I just notice this good literature. It contains most of the work I have read and also includes some recent work that is very informative. Our recent work was published in WSDM 2022 about optimizing the surrogate model through maintaining the Non-Euclidean topology between nodes. 
Here is the link: https://dl.acm.org/doi/10.1145/3488560.3498481. 
We would appreciate it if you would like to add it to the list.

Many thanks

**Comment by YingtongDou** [comment]
Your paper has been added to the list, thanks!

**Comment by Zihan-Liu-00** [comment]
Thanks a lot!
