### ISSUE TITLE
Could you add our recent paper published in IJCAI 2022？

### ISSUE THREAD

**Issue by thuwzy** [safe-graph/graph-adversarial-learning-literature#17]
Your repo has huge influence in the field of graph adversarial attack. It would be great if you can add our recent paper pulished on IJCAI 2022.

Paper: https://arxiv.org/abs/2109.13069
Code: https://github.com/thuwzy/Cluster-Attack

Thanks a lot!

**Comment by YingtongDou** [comment]
The paper has been added to the list, thanks!
