### ISSUE TITLE
Please add our new backdoor attack paper accepted by RAID 2022

### ISSUE THREAD

**Issue by goodman1204** [safe-graph/graph-adversarial-learning-literature#18]
Hi @YingtongDou, 

It will be great if you can add our latest graph backdoor paper accepted by RAID 2022,

"Transferable Graph Backdoor Attack. Shuiqiao Yang, Bao Gia Doan, Paul Montague, Olivier De Vel, Tamas Abraham, Seyit Camtepe, Damith C. Ranasinghe, Salil S. Kanhere"

URL: https://arxiv.org/abs/2207.00425
Thanks.

**Comment by YingtongDou** [comment]
The paper has been added to the list, thanks!

**Comment by goodman1204** [comment]
> The paper has been added to the list, thanks!

@YingtongDou Thanks a lot for your help.
