### ISSUE TITLE
Request for adding two relevant papers

### ISSUE THREAD

**Issue by AndrewZhou924** [safe-graph/graph-adversarial-learning-literature#23]
Hi,

Thanks for maintaining this awesome repo!

I would like to add our works (as follows) to this repo, which are quite relevant.

Paper1
- Title: On Strengthening and Defending Graph Reconstruction Attack with Markov Chain Approximation
- Conference: ICML 2023
- Paper: https://arxiv.org/pdf/2306.09104.pdf
- Code: https://github.com/tmlr-group/MC-GRA

Paper2
- Title: Combating Bilateral Edge Noise for Robust Link Prediction
- Conference: NeurIPS 2023
- Paper: https://arxiv.org/pdf/2311.01196.pdf
- Code: https://github.com/tmlr-group/RGIB

Thanks for your attention.

Best Regards,
Zhanke

**Comment by YingtongDou** [comment]
This repo is currently not actively maintained. Please make PRs by yourself if you want to add new papers. Thank you!
