### ISSUE TITLE
Efficient Robustness Certificates for Discrete Data: Sparsity-Aware Randomized Smoothing for Graphs, Images and More

### ISSUE THREAD

**Issue by abojchevski** [safe-graph/graph-adversarial-learning-literature#4]
Hi,

Thanks for this awesome resource. It's great for keeping up with the literature.

The certificates in our paper "Efficient Robustness Certificates for Discrete Data: Sparsity-Aware Randomized Smoothing for Graphs, Images and More" can handle both node classification and graph classification (we show results on this in the appendix). It would be great if you can update the list to reflect this. 

Thanks

**Comment by YingtongDou** [comment]
Thanks for noting that!

I have updated it to **Robustness Certification** to unify it with other certification papers.
