### ISSUE TITLE
I would be happy if you would add our workshop paper

### ISSUE THREAD

**Issue by sigeisler** [safe-graph/graph-adversarial-learning-literature#6]
Attacking Graph Neural Networks at Scale. Simon Geisler, Daniel Zügner, Aleksandar Bojchevski, Stephan Günnemann. AAAI workshop 2021.

Link https://www.in.tum.de/en/daml/attack-gnn-at-scale/

**Comment by YingtongDou** [comment]
Thanks, I will add it in the next update.
